from airflow.decorators import dag, task
from airflow.utils.dates import days_ago
from datetime import datetime, timedelta
from selenium import webdriver
from selenium.webdriver.chrome.service import Service as ChromeService
from webdriver_manager.chrome import ChromeDriverManager
from webdriver_manager.core.utils import read_version_from_cmd, PATTERN
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import time
import sys
import os
from scraper import search_keywords_in_reddit, scrape_keyword_from_reddit

# sys.path.append(os.path.abspath('..'))

# default_args = {
#     "depends_on_past": False,
#     "retries": 1,
#     "retry_delay": timedelta(minutes=5),
# }


# @dag(
#     default_args = default_args,
#     dag_id="reddit_ingestion",
#     # start_date=days_ago(1),
#     start_date=datetime(2021, 1, 1),
# )
# def reddit_ingestion_dag():

#     @task(task_id="say_id")
#     def print_hi():
#         print("Hi")

#     print_hi()

# reddit_ingestion_dag()


competitors = [
# "WeCloudData",
# "Practicum",
# "Metis",
# "The Data Incubator",
# "NYC Data Science",
# "Data Science Retreat", #
# "BrainStation",
"Thinkful",
"Springboard",
"General Assembly",
"Le Wagon",
"Toronto School of Management",
"Juno College",
"Lighthouse Labs",
]


# competitors = [
#  '4Geeks Academy',
#  'AcadGild',
#  'AccioJob',
#  'Aceamica',
#  'Actualize',
#  'Ada Developers Academy',
#  'Afterskills',
#  'AiCore',
#  'Alchemy Code Lab',
#  'Algonquin College',
#  'Alliance MBS',
#  'Altcademy',
#  'AlwaysHired FREE Bootcamp',
#  'American University Digital Skills',
#  'App Academy',
#  'Aspireship',
#  'Athabasca University',
#  'Austin Coding Academy',
#  'Austin Sales Academy',
#  'Automation Workz',
#  'Avion School',
#  'Avocademy',
#  'Awesome Inc U',
#  'B9lab Academy',
#  'BECKER COLLEGE BOOTCAMPS',
#  'Barcelona Code School',
#  'Basecamp',
#  'BeachCoders®',
#  'Beginex',
#  'Berkeley Executive Ed',
#  'Bethel Tech',
#  'Big Sky Code Academy',
#  'Bloc - NOW THINKFUL',
#  'Blockgeeks',
#  'Bloom Institute of Technology (BloomTech)',
#  'BloomTech',
#  'Bluebird',
#  'Boca Code',
#  'Bogota Bootcamp',
#  'BoiseCodeWorks',
#  'Boolean',
#  'Boolean Careers',
#  'Bottega University',
#  'Bov Academy',
#  'Bow Valley College',
#  'BrainStation',
#  'Burlington Code Academy',
#  'Bygrad',
#  'Byte Academy',
#  'CAVU Scrum Bootcamp',
#  'CCS Learning Academy',
#  'CRMBase',
#  'CSUP BOOTCAMPS',
#  'CYDEO',
#  'Cal Poly Extended Education Coding Bootcamp',
#  'Cal Poly Extended Education Tech Bootcamps',
#  'California State University LB Digital Skills',
#  'Caltech Bootcamps',
#  'Caltech CTME Online Bootcamps',
#  'Cambrian College',
#  'Cambridge Judge Business School',
#  'Cambridge Spark Ltd',
#  'Camosun College',
#  'Camp4',
#  'Canadian College of Technology and Business (CCTB)',
#  'Canadore College',
#  'CareerDash',
#  'CareerFoundry',
#  'CareerHacker Data Analyst Mentorship',
#  'Careerist',
#  'Carleton University',
#  'Carnegie Mellon Exec Ed',
#  'Catalyte',
#  'Centennial College',
#  'Chris Trotzky Bootcamp',
#  'Claim Academy',
#  'Clarusway',
#  'Co.Lab (www.joincolab.io)',
#  'Codaisseur',
#  'Code Career Academy',
#  'Code Chrysalis',
#  'Code Fellows',
#  'Code Institute',
#  'Code Platoon',
#  'Code Stack Academy',
#  'CodeBound™',
#  'CodeBoxx',
#  'CodeCore',
#  'CodeOp',
#  'CodeSpace',
#  'CodeWizardsHQ',
#  'Codeable',
#  'Coder Foundry',
#  'Coder Vox',
#  'Coders Campus',
#  'Coders Lab',
#  'Codesmith',
#  'Codeup',
#  'Codeworks',
#  'Codex Academy',
#  'Codify Academy',
#  'Coding Autism',
#  'Coding Bootcamp Praha',
#  'Coding Dojo',
#  'Coding Experiences',
#  'Coding Invaders by MentorsPro',
#  'Coding Temple',
#  'CodingNomads',
#  'Cogent University',
#  'Colaberry',
#  'Columbia Business School',
#  'Columbia Engineering',
#  'Concordia Bootcamps',
#  'Concordia University',
#  'Conestoga College',
#  'Constructor Learning',
#  'CourseCareers',
#  'Covalence',
#  'Craft Academy',
#  'Código Lab',
#  'Dartmouth Engineering',
#  'Dartmouth Thayer',
#  'Data Analytics & Business Intelligence',
#  'Data Application Lab',
#  'Data Sci & AI with Python',
#  'Data Science Beach Camp',
#  'Data Science Dojo',
#  'Data Science Retreat',
#  'DataCamp',
#  'DataScientest',
#  'Dataquest',
#  'Deep Dive Learning Academy',
#  'Dented Code Academy',
#  'Design Sprint School',
#  'Designation',
#  'Designlab',
#  'DevBootcamp',
#  'DevLeague',
#  'DevX School',
#  'DevelopIntelligence',
#  'Devmountain',
#  'Digital Creative',
#  'Digital Marketing Institute',
#  'DigitalCrafts',
#  'Douglas College',
#  'Durham College',
#  'Elevate SDR Bootcamp',
#  'Eleven Fifty Academy',
#  'Emily Carr University of Art and Design',
#  'Epicodus',
#  'Evolve Academy',
#  'Fanshawe College',
#  'Flatiron School',
#  'Flockjay',
#  'Florida Atlantic Bootcamp',
#  'Forage',
#  'FourthRev',
#  'FreeCodeCamp',
#  'Fuel Sales Academy',
#  'Full-Stack Web Dev Software Training Program',
#  'Fullstack Academy',
#  'Function Camp',
#  'Galvanize',
#  'Geekwise Academy',
#  'GenSpark',
#  'General Assembly',
#  'Generation USA',
#  'George Brown',
#  'Ginger School',
#  'GoIT',
#  'Grace Hopper Program',
#  'Grand Circus',
#  'Great Learning',
#  'GreyAtom School of Data Science',
#  'Greystone College',
#  'Gritly',
#  'Growclass',
#  'Growth Tribe',
#  'HEC Montreal',
#  'Hack Reactor',
#  'Hackbright Academy',
#  'Hacktiv8',
#  'Hackwagon Academy',
#  'High Bridge Academy',
#  'Highway Education',
#  'Hofstra Bootcamps',
#  'Holberton School',
#  'Holyoke Community College Career Bootcamp',
#  'Horizons School',
#  'Humber College',
#  'HyperionDev',
#  'Imperial College London',
#  'Indiana Wesleyan University Cybersecurity Bootcamp',
#  'Insead Exec Ed',
#  'Interview Kickstart',
#  'Inventive',
#  'Ironhack',
#  'James Madison Bootcamps',
#  'Jedha',
#  'Jelly Academy',
#  'Jigsaw Labs',
#  'JobEasy Inc.',
#  'JobPrepped',
#  'Jovian',
#  'Juno College',
#  'Kable Academy',
#  'Kansas State University Digital Skills Bootcamps',
#  'KeepCoding',
#  'Kellogg Executive Education',
#  'Kenzie Academy - Full Stack Development',
#  'Kenzie Academy - Software Engineering',
#  'Kodigo Code Camp',
#  'LDA (Learn Data Analytics)',
#  'La Cité',
#  'LaSalle College',
#  'Lambton College',
#  'Langara College',
#  'Launch Academy',
#  'Launch School',
#  'LaunchCode',
#  'Le Wagon',
#  'Lead Academy',
#  'LearningFuze Coding and Data Science Bootcamp',
#  'Level Effect',
#  'Lighthouse Labs',
#  'London Business School',
#  'Louisiana State University',
#  'Louisiana State University Online Bootcamps',
#  'Loyalist College',
#  'Loyola University New Orleans Digital Skills',
#  'MAX Technical Training',
#  'MAXimum Coding Bootcamp',
#  'MIT PE',
#  'MIT Schwarzman College of Computing',
#  'MIT Sloan Exec Ed',
#  'MIT xPRO',
#  'MacEwan University',
#  'Make School',
#  'Makerpad',
#  'Makers Academy',
#  'Maricopa Corporate College',
#  'Masai School',
#  'Mate academy',
#  'McGill University',
#  'Mente Argentina',
#  'Merit America',
#  'Metis',
#  'Miami Ad School',
#  'Microverse',
#  'MilSpo Academy',
#  'Millionlights University',
#  'MindHub',
#  'Mindteck Academy',
#  'Mohawk College',
#  'Momentum',
#  'Mount Royal University',
#  'NEXT Academy',
#  'NGT Academy',
#  'NYC Data Science Academy',
#  'NYU Bootcamps',
#  'NYU SPS Cybersecurity Bootcamp',
#  'Nashville Software School',
#  'National University Bootcamp',
#  'Neoland',
#  'New Jersey Institute of Technology Digital Skills',
#  'Nexus at University of Michigan Engineering',
#  'Niagara College',
#  'Noble Desktop',
#  'Nod Coding Bootcamp',
#  'North Carolina State University Digital Skills',
#  'Northcoders',
#  'Nova Scotia Community College',
#  'Nucamp',
#  'OCAD University',
#  'Old Dominion University Digital Skills',
#  'OpenClassrooms',
#  'Osmi Pro',
#  'PDX Code Guild',
#  'PMDojo (www.pmdojo.me/apply)',
#  'Parsity',
#  'Path Unbound School of Design',
#  'Pathstream',
#  'Pepperdine University Digital Skills',
#  'Per Scholas',
#  'Perpetual Education',
#  'Pipeline Academy',
#  'Pivot Technology School',
#  'Pluralsight',
#  'Practicum: Coding bootcamps',
#  'Pragra',
#  'PreSales Academy',
#  'Prehired',
#  'Product Gym',
#  'Product Hall',
#  'Product Mastermind',
#  'Product School',
#  'Promotable',
#  'Propulsion Academy',
#  'PunchCode',
#  'Pursuit',
#  'QAinUSA',
#  'Qwasar Silicon Valley',
#  'RMOTR',
#  'RareSkills',
#  'React GraphQL Academy',
#  'Refactory',
#  'Reify Academy',
#  'Rithm School',
#  'Rotman University',
#  'Rutgers Professional & Executive Ed Programs',
#  'S.O. Accelerated Learning',
#  'SE Factory',
#  'SNHU',
#  'SV Academy',
#  'Sabio',
#  'Sales Bootcamp',
#  'San Diego Global Knowledge University',
#  'San Diego State University Digital Skills',
#  'Santa Clara Bootcamps',
#  'Satellite',
#  'Sault College',
#  'Scaler',
#  'School of IT',
#  'Schulich ExecEd',
#  'Schulich School of Business',
#  'Science to Data Science',
#  'Seneca College',
#  'SheCodes',
#  'Sheridan College',
#  'Shillington',
#  'Simon Fraser University',
#  'Simon Fraser University Continuing Studies',
#  'Simplilearn',
#  'Skill Distillery',
#  'SkillBank',
#  'SkillReactor',
#  'Skillcrush',
#  'Skills Union',
#  'Skillspire',
#  'Skylab Coders Academy',
#  "Smith School of Business at Queen's University",
#  'SoftStack Factory',
#  'SoloLearn',
#  'Southern Alberta Institute of Technology (SAIT)',
#  'Sparka Academy',
#  'Springboard',
#  'Springfield Technical Community College Career Bootcamp',
#  'Sprott Shaw College',
#  'St. Clair College',
#  'St. Lawrence College',
#  'Strive School',
#  'Suncoast Devs',
#  'TECH I.S.',
#  'Tech Bootcamps at University of North Florida',
#  'Tech Career Booster',
#  'Tech Elevator',
#  'Tech Talent South',
#  'TechPro Education',
#  'Techlent',
#  'Technosoft Academy',
#  'Techtonica',
#  'Techtorial',
#  'Test Pro',
#  'Texas A&M University Bootcamp',
#  'The Bridge',
#  'The Data Incubator',
#  'The Dev Masters',
#  'The G. Raymond Chang School of Continuing Education, Toronto Metropolitan University',
#  'The Hacking School',
#  'The Institute for Statistics Education',
#  'The Jump Digital School',
#  'The Odin Project',
#  'The Ohio State University Boot Camps',
#  'The Praxis Apprenticeship Program',
#  'The Software Guild',
#  'The Tech Academy',
#  'Thinkful',
#  'Toronto Film School',
#  'Toronto Metropolitan University',
#  'Toronto School of Management (TSoM)',
#  'Touro University Graduate School of Technology',
#  'Trebas Institute',
#  'Treehouse',
#  'Trent University',
#  'TrueCoders',
#  'Turing College',
#  'Turing School',
#  'UBC Extended Learning',
#  'UC San Diego Extended Studies Online Bootcamps',
#  'UCI Online Bootcamps',
#  'UMGC Online Bootcamps',
#  'UMass Amherst Online Bootcamps',
#  'UMass Global Online Bootcamps',
#  'UNF Division of Continuing Education Bootcamps',
#  'USD Professional and Continuing Education Coding Bootcamp',
#  'UWM School of Continuing Education Coding Bootcamp',
#  'UX Academy',
#  'UX Design Institute',
#  'UXER School',
#  'Ubiqum Code Academy',
#  'Udacity',
#  'Umuzi Academy',
#  'University Canada West (UCW)',
#  'University at Buffalo Digital Skills',
#  'University of Alberta',
#  'University of British Columbia',
#  'University of Calgary',
#  'University of Central Florida Digital Skills',
#  'University of Colorado Boulder Digital Skills',
#  'University of Miami Digital Skills',
#  'University of Nevada, Las Vegas Digital Skills',
#  'University of New Hampshire Online Bootcamps',
#  'University of San Diego Tech Bootcamp',
#  'University of San Diego Tech Bootcamps',
#  'University of South Florida CTPE Online Bootcamps',
#  'University of Toronto',
#  'University of Toronto School of Continuing Studies',
#  'University of Waterloo',
#  'University of Winnipeg',
#  'University of Wisconsin-Madison Digital Bootcamps',
#  'Uplift Code Camp',
#  'Uvaro Tech sales',
#  'V School',
#  'ValleyML Fellowship',
#  'Vancouver Film School (VFS)',
#  'Vancouver Institute of Media Arts',
#  'Vault Academy',
#  'Victory Lap',
#  'Wagner College Bootcamps',
#  'We Can Code IT',
#  'WeCloudData',
#  'WeStride',
#  'WeThinkCode_',
#  'Western University',
#  'Wharton Exec Ed',
#  'WorldQuant University',
#  'Woz U',
#  'Wyncode Academy',
#  'Xccelerate',
#  'Xperian School',
#  'Yellow Tail Tech',
#  'York University School of Continuing Studies',
#  'Zip Code Wilmington',
#  'Zuitt Coding Bootcamp',
#  'a2zTechCon',
#  'acaDev',
#  'allWomen',
#  'devCodeCamp',
#  'iXperience',
#  'inTellee College',
#  'upGrad',
#  'wcoding']



# The DAG object; we'll need this to instantiate a DAG
from airflow import DAG

# Operators; we need this to operate!
from airflow.operators.bash import BashOperator
with DAG(
    "tutorial",
    # These args will get passed on to each operator
    # You can override them on a per-task basis during operator initialization
    default_args={
        "depends_on_past": False,
        "email": ["airflow@example.com"],
        "email_on_failure": False,
        "email_on_retry": False,
        "retries": 1,
        "retry_delay": timedelta(minutes=5),
        # 'queue': 'bash_queue',
        # 'pool': 'backfill',
        # 'priority_weight': 10,
        # 'end_date': datetime(2016, 1, 1),
        # 'wait_for_downstream': False,
        # 'sla': timedelta(hours=2),
        # 'execution_timeout': timedelta(seconds=300),
        # 'on_failure_callback': some_function,
        # 'on_success_callback': some_other_function,
        # 'on_retry_callback': another_function,
        # 'sla_miss_callback': yet_another_function,
        # 'trigger_rule': 'all_success'
    },
    description="A simple tutorial DAG",
    schedule_interval=timedelta(days=1),
    start_date=datetime(2021, 1, 1),
    catchup=False,
    tags=["example"],
) as dag:

    @task(task_id="say_id")
    def print_hi():
        print("Hi")

    @task(task_id="launching_chrome")
    def launch_chrome():
        chrome_options = Options()  
        # options = webdriver.ChromeOptions()
        # options.add_argument("–ignore-ssl-errors=yes")
        # options.add_argument("–ignore-certificate-errors")
        chrome_options.add_argument("--headless")  
        chrome_options.add_argument("--no-sandbox")
        chrome_options.add_argument("--disable-dev-shm-usage")
        chrome_options.add_argument("--start-maximized")
        chrome_options.add_argument("--start-fullscreen")
        chrome_options.add_argument("--no-proxy-server")
        chrome_options.add_argument("--proxy-server='direct://'")
        chrome_options.add_argument("--proxy-bypass-list=*")
        # driver = webdriver.Remote(command_executor="http://localhost:4444/", options=chrome_options)
        driver = webdriver.Chrome(ChromeDriverManager().install(), options=chrome_options)
        # driver = webdriver.Chrome(executable_path="/usr/local/bin/chromedriver")
        time.sleep(5)
        driver.get("https://www.reddit.com/?feed=home")
        time.sleep(5)
        h3 = driver.find_element('xpath', '/html/body/div[1]/div/div[2]/div[2]/div/div/div/div[2]/div[2]/div[1]/div[3]/div[1]/div/div/div[3]/div[2]/div[1]/a/div/h3')
                                        
        print(h3.text)


    @task(task_id="scraping")
    def scrape_test():
        scrape_keyword_from_reddit(competitors) # starlights waz

    
    @task(task_id="store_to_database")
    def store_to_database():
        query = ""
        # execute
        # commit

    t4 = print_hi()
    t5 = scrape_test()

    t4 >> t5

#     t1 >> [t2, t3]